2021-05-27T11:39:07|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\ScopeFoundryProjects\PROCHIP microscope\HexSIM_Analyser\HexSimAnalyser_measurement.py", line 30, in inner
    result = function(cls)
  File "C:\LabPrograms\Python\ScopeFoundryProjects\PROCHIP microscope\HexSIM_Analyser\HexSimAnalyser_measurement.py", line 349, in calibration
    self.h.calibrate(self.imageRaw,self.isFindCarrier)
  File "C:\LabPrograms\Python\ScopeFoundryProjects\PROCHIP microscope\HexSimProcessor\SIM_processing\hexSimProcessor.py", line 90, in calibrate
    self._calibrate(img, findCarrier, useCupy = False)
  File "C:\LabPrograms\Python\ScopeFoundryProjects\PROCHIP microscope\HexSimProcessor\SIM_processing\hexSimProcessor.py", line 133, in _calibrate
    sum_prepared_comp[k, :, :] = sum_prepared_comp[k, :, :] + imgs[l, :, :] * M[k, l]
ValueError: operands could not be broadcast together with shapes (1200,1200) (1200,1920) 

